// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type BankAccount struct {
	ID        int32
	UserID    int32
	Name      string
	Balance   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Bitcoin struct {
	ID            int32
	BankAccountID int32
	PurchasePrice string
	Quantity      string
	PurchaseDate  time.Time
}

type FixedExpense struct {
	ID            int32
	BankAccountID int32
	Amount        string
	Description   string
}

type Investment struct {
	ID            int32
	BankAccountID int32
	Amount        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Loan struct {
	ID            int32
	BankAccountID int32
	Amount        string
	InterestRate  string
	DueDate       time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Transaction struct {
	ID            int32
	BankAccountID int32
	Amount        string
	Timestamp     time.Time
	Description   string
	CreditDebit   bool
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
